/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Anti-Patterns',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'patterns',
        },
      ],
    },
    'contributing',
  ],
};

export default sidebars;
