/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  patternsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'patterns',
    },
    {
      type: 'doc',
      id: 'contributing',
    },
  ],
};

export default sidebars;
